[web]
192.168.200.51 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[app]
192.168.200.52 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[db]
192.168.200.53 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no
